/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as dashboardGeneralUserDashBoardRouteImport } from './routes/(dashboard)/generalUserDashBoard'
import { Route as dashboardAdminDashboardRouteImport } from './routes/(dashboard)/adminDashboard'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authMfaRouteImport } from './routes/(auth)/mfa'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgotPassword'
import { Route as dashboardorganisationOrganizationsOperatorsRouteImport } from './routes/(dashboard)/(organisation)/organizationsOperators'
import { Route as dashboardorganisationOrganizationsBillingRouteImport } from './routes/(dashboard)/(organisation)/organizationsBilling'
import { Route as dashboardorganisationOrganizationsRouteImport } from './routes/(dashboard)/(organisation)/organizations'
import { Route as dashboardorganisationOrganizationProfileRouteImport } from './routes/(dashboard)/(organisation)/organizationProfile'
import { Route as dashboardorganisationOrganizationDashboardRouteImport } from './routes/(dashboard)/(organisation)/organizationDashboard'
import { Route as dashboardorganisationOrganisationDashboardNewRouteImport } from './routes/(dashboard)/(organisation)/organisationDashboard/new'
import { Route as dashboardorganisationOrganisationDashboardIdRouteImport } from './routes/(dashboard)/(organisation)/organisationDashboard/$id'
import { Route as dashboardorganisationOrganisationIdRouteImport } from './routes/(dashboard)/(organisation)/organisation/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardGeneralUserDashBoardRoute =
  dashboardGeneralUserDashBoardRouteImport.update({
    id: '/(dashboard)/generalUserDashBoard',
    path: '/generalUserDashBoard',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardAdminDashboardRoute = dashboardAdminDashboardRouteImport.update({
  id: '/(dashboard)/adminDashboard',
  path: '/adminDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authMfaRoute = authMfaRouteImport.update({
  id: '/(auth)/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardorganisationOrganizationsOperatorsRoute =
  dashboardorganisationOrganizationsOperatorsRouteImport.update({
    id: '/(dashboard)/(organisation)/organizationsOperators',
    path: '/organizationsOperators',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardorganisationOrganizationsBillingRoute =
  dashboardorganisationOrganizationsBillingRouteImport.update({
    id: '/(dashboard)/(organisation)/organizationsBilling',
    path: '/organizationsBilling',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardorganisationOrganizationsRoute =
  dashboardorganisationOrganizationsRouteImport.update({
    id: '/(dashboard)/(organisation)/organizations',
    path: '/organizations',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardorganisationOrganizationProfileRoute =
  dashboardorganisationOrganizationProfileRouteImport.update({
    id: '/(dashboard)/(organisation)/organizationProfile',
    path: '/organizationProfile',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardorganisationOrganizationDashboardRoute =
  dashboardorganisationOrganizationDashboardRouteImport.update({
    id: '/(dashboard)/(organisation)/organizationDashboard',
    path: '/organizationDashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardorganisationOrganisationDashboardNewRoute =
  dashboardorganisationOrganisationDashboardNewRouteImport.update({
    id: '/(dashboard)/(organisation)/organisationDashboard/new',
    path: '/organisationDashboard/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardorganisationOrganisationDashboardIdRoute =
  dashboardorganisationOrganisationDashboardIdRouteImport.update({
    id: '/(dashboard)/(organisation)/organisationDashboard/$id',
    path: '/organisationDashboard/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardorganisationOrganisationIdRoute =
  dashboardorganisationOrganisationIdRouteImport.update({
    id: '/(dashboard)/(organisation)/organisation/$id',
    path: '/organisation/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/forgotPassword': typeof authForgotPasswordRoute
  '/mfa': typeof authMfaRoute
  '/sign-in': typeof authSignInRoute
  '/adminDashboard': typeof dashboardAdminDashboardRoute
  '/generalUserDashBoard': typeof dashboardGeneralUserDashBoardRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/organizationDashboard': typeof dashboardorganisationOrganizationDashboardRoute
  '/organizationProfile': typeof dashboardorganisationOrganizationProfileRoute
  '/organizations': typeof dashboardorganisationOrganizationsRoute
  '/organizationsBilling': typeof dashboardorganisationOrganizationsBillingRoute
  '/organizationsOperators': typeof dashboardorganisationOrganizationsOperatorsRoute
  '/organisation/$id': typeof dashboardorganisationOrganisationIdRoute
  '/organisationDashboard/$id': typeof dashboardorganisationOrganisationDashboardIdRoute
  '/organisationDashboard/new': typeof dashboardorganisationOrganisationDashboardNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/forgotPassword': typeof authForgotPasswordRoute
  '/mfa': typeof authMfaRoute
  '/sign-in': typeof authSignInRoute
  '/adminDashboard': typeof dashboardAdminDashboardRoute
  '/generalUserDashBoard': typeof dashboardGeneralUserDashBoardRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/organizationDashboard': typeof dashboardorganisationOrganizationDashboardRoute
  '/organizationProfile': typeof dashboardorganisationOrganizationProfileRoute
  '/organizations': typeof dashboardorganisationOrganizationsRoute
  '/organizationsBilling': typeof dashboardorganisationOrganizationsBillingRoute
  '/organizationsOperators': typeof dashboardorganisationOrganizationsOperatorsRoute
  '/organisation/$id': typeof dashboardorganisationOrganisationIdRoute
  '/organisationDashboard/$id': typeof dashboardorganisationOrganisationDashboardIdRoute
  '/organisationDashboard/new': typeof dashboardorganisationOrganisationDashboardNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/(auth)/forgotPassword': typeof authForgotPasswordRoute
  '/(auth)/mfa': typeof authMfaRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(dashboard)/adminDashboard': typeof dashboardAdminDashboardRoute
  '/(dashboard)/generalUserDashBoard': typeof dashboardGeneralUserDashBoardRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(dashboard)/(organisation)/organizationDashboard': typeof dashboardorganisationOrganizationDashboardRoute
  '/(dashboard)/(organisation)/organizationProfile': typeof dashboardorganisationOrganizationProfileRoute
  '/(dashboard)/(organisation)/organizations': typeof dashboardorganisationOrganizationsRoute
  '/(dashboard)/(organisation)/organizationsBilling': typeof dashboardorganisationOrganizationsBillingRoute
  '/(dashboard)/(organisation)/organizationsOperators': typeof dashboardorganisationOrganizationsOperatorsRoute
  '/(dashboard)/(organisation)/organisation/$id': typeof dashboardorganisationOrganisationIdRoute
  '/(dashboard)/(organisation)/organisationDashboard/$id': typeof dashboardorganisationOrganisationDashboardIdRoute
  '/(dashboard)/(organisation)/organisationDashboard/new': typeof dashboardorganisationOrganisationDashboardNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/settings'
    | '/forgotPassword'
    | '/mfa'
    | '/sign-in'
    | '/adminDashboard'
    | '/generalUserDashBoard'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/organizationDashboard'
    | '/organizationProfile'
    | '/organizations'
    | '/organizationsBilling'
    | '/organizationsOperators'
    | '/organisation/$id'
    | '/organisationDashboard/$id'
    | '/organisationDashboard/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/settings'
    | '/forgotPassword'
    | '/mfa'
    | '/sign-in'
    | '/adminDashboard'
    | '/generalUserDashBoard'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/organizationDashboard'
    | '/organizationProfile'
    | '/organizations'
    | '/organizationsBilling'
    | '/organizationsOperators'
    | '/organisation/$id'
    | '/organisationDashboard/$id'
    | '/organisationDashboard/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/settings'
    | '/(auth)/forgotPassword'
    | '/(auth)/mfa'
    | '/(auth)/sign-in'
    | '/(dashboard)/adminDashboard'
    | '/(dashboard)/generalUserDashBoard'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(dashboard)/(organisation)/organizationDashboard'
    | '/(dashboard)/(organisation)/organizationProfile'
    | '/(dashboard)/(organisation)/organizations'
    | '/(dashboard)/(organisation)/organizationsBilling'
    | '/(dashboard)/(organisation)/organizationsOperators'
    | '/(dashboard)/(organisation)/organisation/$id'
    | '/(dashboard)/(organisation)/organisationDashboard/$id'
    | '/(dashboard)/(organisation)/organisationDashboard/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SettingsRoute: typeof SettingsRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authMfaRoute: typeof authMfaRoute
  authSignInRoute: typeof authSignInRoute
  dashboardAdminDashboardRoute: typeof dashboardAdminDashboardRoute
  dashboardGeneralUserDashBoardRoute: typeof dashboardGeneralUserDashBoardRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  dashboardorganisationOrganizationDashboardRoute: typeof dashboardorganisationOrganizationDashboardRoute
  dashboardorganisationOrganizationProfileRoute: typeof dashboardorganisationOrganizationProfileRoute
  dashboardorganisationOrganizationsRoute: typeof dashboardorganisationOrganizationsRoute
  dashboardorganisationOrganizationsBillingRoute: typeof dashboardorganisationOrganizationsBillingRoute
  dashboardorganisationOrganizationsOperatorsRoute: typeof dashboardorganisationOrganizationsOperatorsRoute
  dashboardorganisationOrganisationIdRoute: typeof dashboardorganisationOrganisationIdRoute
  dashboardorganisationOrganisationDashboardIdRoute: typeof dashboardorganisationOrganisationDashboardIdRoute
  dashboardorganisationOrganisationDashboardNewRoute: typeof dashboardorganisationOrganisationDashboardNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/generalUserDashBoard': {
      id: '/(dashboard)/generalUserDashBoard'
      path: '/generalUserDashBoard'
      fullPath: '/generalUserDashBoard'
      preLoaderRoute: typeof dashboardGeneralUserDashBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/adminDashboard': {
      id: '/(dashboard)/adminDashboard'
      path: '/adminDashboard'
      fullPath: '/adminDashboard'
      preLoaderRoute: typeof dashboardAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/mfa': {
      id: '/(auth)/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof authMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgotPassword': {
      id: '/(auth)/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/(organisation)/organizationsOperators': {
      id: '/(dashboard)/(organisation)/organizationsOperators'
      path: '/organizationsOperators'
      fullPath: '/organizationsOperators'
      preLoaderRoute: typeof dashboardorganisationOrganizationsOperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/(organisation)/organizationsBilling': {
      id: '/(dashboard)/(organisation)/organizationsBilling'
      path: '/organizationsBilling'
      fullPath: '/organizationsBilling'
      preLoaderRoute: typeof dashboardorganisationOrganizationsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/(organisation)/organizations': {
      id: '/(dashboard)/(organisation)/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof dashboardorganisationOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/(organisation)/organizationProfile': {
      id: '/(dashboard)/(organisation)/organizationProfile'
      path: '/organizationProfile'
      fullPath: '/organizationProfile'
      preLoaderRoute: typeof dashboardorganisationOrganizationProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/(organisation)/organizationDashboard': {
      id: '/(dashboard)/(organisation)/organizationDashboard'
      path: '/organizationDashboard'
      fullPath: '/organizationDashboard'
      preLoaderRoute: typeof dashboardorganisationOrganizationDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/(organisation)/organisationDashboard/new': {
      id: '/(dashboard)/(organisation)/organisationDashboard/new'
      path: '/organisationDashboard/new'
      fullPath: '/organisationDashboard/new'
      preLoaderRoute: typeof dashboardorganisationOrganisationDashboardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/(organisation)/organisationDashboard/$id': {
      id: '/(dashboard)/(organisation)/organisationDashboard/$id'
      path: '/organisationDashboard/$id'
      fullPath: '/organisationDashboard/$id'
      preLoaderRoute: typeof dashboardorganisationOrganisationDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/(organisation)/organisation/$id': {
      id: '/(dashboard)/(organisation)/organisation/$id'
      path: '/organisation/$id'
      fullPath: '/organisation/$id'
      preLoaderRoute: typeof dashboardorganisationOrganisationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SettingsRoute: SettingsRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authMfaRoute: authMfaRoute,
  authSignInRoute: authSignInRoute,
  dashboardAdminDashboardRoute: dashboardAdminDashboardRoute,
  dashboardGeneralUserDashBoardRoute: dashboardGeneralUserDashBoardRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  dashboardorganisationOrganizationDashboardRoute:
    dashboardorganisationOrganizationDashboardRoute,
  dashboardorganisationOrganizationProfileRoute:
    dashboardorganisationOrganizationProfileRoute,
  dashboardorganisationOrganizationsRoute:
    dashboardorganisationOrganizationsRoute,
  dashboardorganisationOrganizationsBillingRoute:
    dashboardorganisationOrganizationsBillingRoute,
  dashboardorganisationOrganizationsOperatorsRoute:
    dashboardorganisationOrganizationsOperatorsRoute,
  dashboardorganisationOrganisationIdRoute:
    dashboardorganisationOrganisationIdRoute,
  dashboardorganisationOrganisationDashboardIdRoute:
    dashboardorganisationOrganisationDashboardIdRoute,
  dashboardorganisationOrganisationDashboardNewRoute:
    dashboardorganisationOrganisationDashboardNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
