/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authMfaRouteImport } from './routes/(auth)/mfa'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgotPassword'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authMfaRoute = authMfaRouteImport.update({
  id: '/(auth)/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgotPassword': typeof authForgotPasswordRoute
  '/mfa': typeof authMfaRoute
  '/sign-in': typeof authSignInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgotPassword': typeof authForgotPasswordRoute
  '/mfa': typeof authMfaRoute
  '/sign-in': typeof authSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(auth)/forgotPassword': typeof authForgotPasswordRoute
  '/(auth)/mfa': typeof authMfaRoute
  '/(auth)/sign-in': typeof authSignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/forgotPassword' | '/mfa' | '/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/forgotPassword' | '/mfa' | '/sign-in'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(auth)/forgotPassword'
    | '/(auth)/mfa'
    | '/(auth)/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authMfaRoute: typeof authMfaRoute
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/mfa': {
      id: '/(auth)/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof authMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgotPassword': {
      id: '/(auth)/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authMfaRoute: authMfaRoute,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
